### List users

GET http://localhost:3001/users

### Create user

POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "joaovic921@gmail.com",
}

### Find user by id

GET http://localhost:3001/users/1


### Update user by id

PUT http://localhost:3001/users/1
Content-Type: application/json

{
  "email": "joao3vic921@gmail.com",
}

### Delete user by id

DELETE http://localhost:3001/users/1